services:
  whisperx-api:
    container_name: whisperx-api
    build: .
    # image: ghcr.io/xudongcc/whisperx-api:latest
    ports:
      - "8000:8000"
    environment:
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      - ~/.cache:/root/.cache
